import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { API_RESPONSE } from 'pages/api/api-constants';
import { useState, useEffect } from 'react';
import { useWalletConnectClient } from '../components/contexts/ClientContext';

// 商業施設の店舗情報（デモ用に固定値を利用）
const SHOP_INFO = [
  { value: 0, building: 'Tokyo Torch', location: '東京', shopName: '店舗A' },
  { value: 1, building: '大名古屋ビル', location: '愛知', shopName: '店舗B' },
  { value: 2, building: 'OAPプラザ', location: '大阪', shopName: '店舗C' },
];

export default function CreateCommunity() {
  const { accounts } = useWalletConnectClient();

  const [inputData, setInputData] = useState({
    communityName: '',
    description: '',
    building: '',
    shopName: '',
    location: '',
    capacity: '',
    expire: 'Sun Dec 31 2023 21:00:00',
  });
  const [selectedIndex, setSelectedIndex] = useState(0);

  const router = useRouter();

  // コミュニティ情報をDBに格納するAPI
  const setCommunityAPI = async () => {
    try {
      // APIの実行
      const res = await fetch(`/api/community/setCommunity`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          owner: accounts[0].toLowerCase(),
          communityName: inputData.communityName,
          description: inputData.description,
          building: SHOP_INFO[selectedIndex].building,
          shopName: SHOP_INFO[selectedIndex].shopName,
          location: SHOP_INFO[selectedIndex].location,
          capacity: inputData.capacity,
          expire: inputData.expire,
        }),
      });

      // API ステータスコードのチェック
      if (res.status != API_RESPONSE.CREATED.CODE) {
        alert('DBエラーが発生したため、コミュニティを登録出来ませんでした。');
        return;
      }
      alert('コミュニティが作成されました。');
      router.push('/menu');
    } catch (e) {
      console.log(e);
      alert('DBエラーが発生したため、コミュニティを登録出来ませんでした。');
    }
  };

  const onChangeCommunityInputData = (event) => {
    setInputData((prevData) => ({
      ...prevData,
      [event.target.name]: event.target.value,
    }));
  };

  return (
    <>
      <div className={'mx-[20px] my-[24px] min-h-[calc(100vh)]'}>
        <Head>
          <title>CREATE COMMUNITY</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <div className='flex flex-row justify-start items-center'>
          <Image
            src={`/new-design/backBtn.svg`}
            style={{ objectFit: 'obtain' }}
            width={45}
            height={45}
            onClick={() => router.push('/menu')}
            alt='back-btn'
          />
          <p className='text-[#4C4948] font-[700] text-[20px] break-words ml-[12px] leading-[calc(100%)]'>
            コミュニティ作成
          </p>
        </div>

        <div className='mt-[40px]'>
          <div className='mt-[32px]'>
            <p className='text-[#4C4948] font-[600] text-[14px] leading-[calc(100%)]'>
              コミュニティ名
            </p>
          </div>
          <div className='mt-[8px] p-[8px] bg-white border-[1px] border-[#22A9BC]'>
            <input
              type='text'
              className='w-[calc(100%)] h-[22px] text-left text-[14px] text-[#4C4948]'
              name='communityName'
              placeholder={`木曜ランチ会`}
              onChange={onChangeCommunityInputData}
              value={inputData.communityName}
            />
          </div>

          <div className='mt-[32px]'>
            <p className='text-[#4C4948] font-[600] text-[14px] leading-[calc(100%)]'>
              コミュニティの説明
            </p>
          </div>
          <div className='mt-[8px] p-[8px] bg-white border-[1px] border-[#22A9BC]'>
            <input
              type='text'
              className='w-[calc(100%)] h-[22px] text-left text-[14px] text-[#4C4948]'
              name='description'
              placeholder={`人材交流を目的とした、木曜日のランチ会です。`}
              onChange={onChangeCommunityInputData}
              value={inputData.description}
            />
          </div>

          <div className='mt-[32px]'>
            <p className='text-[#4C4948] font-[600] text-[14px] leading-[calc(100%)]'>
              施設名
            </p>
          </div>
          <div className='mt-[8px] p-[8px] bg-white border-[1px] border-[#22A9BC]'>
            <select
              value={selectedIndex}
              onChange={(e) => setSelectedIndex(e.target.value)}
            >
              {SHOP_INFO.map((v, i) => (
                <option key={i} value={v.value}>
                  {v.building}
                </option>
              ))}
            </select>
          </div>

          <div className='mt-[32px]'>
            <p className='text-[#4C4948] font-[600] text-[14px] leading-[calc(100%)]'>
              所在地
            </p>
          </div>
          <div className='mt-[8px] p-[8px] bg-white border-[1px] border-[#22A9BC]'>
            <select
              value={selectedIndex}
              onChange={(e) => setSelectedIndex(e.target.value)}
            >
              {SHOP_INFO.map((v, i) => (
                <option key={i} value={v.value}>
                  {v.location}
                </option>
              ))}
            </select>
          </div>

          <div className='mt-[32px]'>
            <p className='text-[#4C4948] font-[600] text-[14px] leading-[calc(100%)]'>
              店舗名
            </p>
          </div>
          <div className='mt-[8px] p-[8px] bg-white border-[1px] border-[#22A9BC]'>
            <select
              value={selectedIndex}
              onChange={(e) => setSelectedIndex(e.target.value)}
            >
              {SHOP_INFO.map((v, i) => (
                <option key={i} value={v.value}>
                  {v.shopName}
                </option>
              ))}
            </select>
          </div>

          <div className='mt-[32px]'>
            <p className='text-[#4C4948] font-[600] text-[14px] leading-[calc(100%)]'>
              定員
            </p>
          </div>
          <div className='mt-[8px] p-[8px] bg-white border-[1px] border-[#22A9BC]'>
            <input
              type='number'
              className='w-[calc(100%)] h-[22px] text-left text-[14px] text-[#4C4948]'
              name='capacity'
              placeholder={`10人`}
              onChange={onChangeCommunityInputData}
              value={inputData.capacity}
            />
          </div>

          <div className='mt-[32px]'>
            <p className='text-[#4C4948] font-[600] text-[14px] leading-[calc(100%)]'>
              有効期限
            </p>
          </div>
          <div className='mt-[8px] p-[8px] bg-gray-200 border-[1px] border-[#22A9BC]'>
            <input
              type='text'
              className='w-[calc(100%)] h-[22px] text-left text-[14px] text-[#4C4948] bg-gray-200'
              name='expire'
              placeholder={`Sun Dec 31 2023 21:00:00`}
              value={inputData.expire}
            />
          </div>
        </div>

        <div className='mt-[40px]'>
          <div
            className={
              'w-[calc(100%)] h-[45px] flex justify-center items-center'
            }
          >
            <div
              className='w-[calc(100%)] h-[45px] rounded-[10px] bg-[#4C4948] flex justify-center space-x-[10px] items-center'
              onClick={setCommunityAPI}
            >
              <p className='text-white font-[500] text-[18px]'>
                コミュニティを作成する
              </p>
            </div>
          </div>
        </div>

        <div className={`fixed top-0 left-0 w-full h-screen z-[-1]`}>
          <Image
            src={`/background.png`}
            layout={`fill`}
            objectFit={`cover`}
            alt='back-image'
          />
        </div>
      </div>
    </>
  );
}
